### ISSUE TITLE
Dehashed Error - can only concactenate str (not "int") to str

### ISSUE THREAD

**Issue by S7ace** [khast3x/h8mail#109]
*Issues not respecting the issue template will be closed without being read, thank you.*

### Checkbox

- [x] I have thoroughly checked the answer is not in the [wiki](https://github.com/khast3x/h8mail/wiki).

### Env

* h8mail version: 2.5.4
* Python version: 3.9
* Operating System: Debian 

### Description

I've had the same Dehashed error for a long time, across multiple versions.

At the end of the search I get an error that says:

[!] Dehashed error with *email*
can only concatenate str (not "int") to str

### What I Did

h8mail -t *target .txt file* -c *h8mail_config.ini*

**Comment by SpenQ** [comment]
fixed the error in https://github.com/khast3x/h8mail/pull/110
But I'm not sure why Dehashed is returning a 403, this should not happen afaik.

**Comment by SpenQ** [comment]
I just received a message from dehashed that they fixed this issue.

**Comment by rzwolf** [comment]
Hi, 

I got a similar issue I'll show you below: 

h8mail -t email.com -q email.com -c h8mail_config.ini

[>] h8mail is up to date
[~] Removing duplicates
[>] Targets:
[>] email.com
[>] scylla.sh is up
[~] Target factory started for email.com 
[~] [email.com]>[dehashed]
**[!] Dehashed error with email.com 
'total'**

email.com it's just an example to write here.

**Comment by S7ace** [comment]
Hey, just an update to this one:

Still getting an error with the new 2.5.5.

[!] Dehashed error with joe.bloggs@joebloggs.blogs
can only concatenate str (not "int") to str

Also Scylla.sh has been giving an error for the last month or so:

[~] scylla.so is down, skipping

Happy to open a separate issue for that one if needs be.

Thanks for the work on the new Version :)

**Comment by khast3x** [comment]
Ah shoot I though this got fixed but seems not. Thanks for the heads up.  
Did you use any special query (`-q`) when executing h8mail with dehashed @S7ace ?  

Cheers

**Comment by S7ace** [comment]
No nothing out of the usual Syntax:

h8mail -t target.txt -c h8mail-config.ini 

And yeah I noticed that scylla is going through some changed so that's cool - want those password back!!

**Comment by khast3x** [comment]
So it seems this error only happens when dehashed has no results for the targeted email. If dehashed does have data from the target, h8mail should work as intended.  
This issue should be fixed in the next release

**Comment by S7ace** [comment]
Ok great.

On that note, just to make you aware I have use h8mail on a same set of targets that I have used directly with dehashed and have had no results in h8mail, when I have in dehashed. 

Hopefully we're all good in the next release though!

**Comment by johnmerced** [comment]
+1 Looking forward for this fix!
